name: Python package

on: [push, pull_request]

jobs:
    test-jupyter-server:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.10", "3.12"]
        
        steps:
        - name: Check out repository
          uses: actions/checkout@v4

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest jupyter_server_proxy jupyter_server

        - name: Run tests
          run: |
            pytest jupyter_sparkui_proxy/init_test.py
    
    test-notebook:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                python-version: ["3.10", "3.12"]
        
        steps:
        - name: Check out repository
          uses: actions/checkout@v4

        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pytest jupyter_server_proxy notebook

        - name: Run tests
          run: |
            pytest jupyter_sparkui_proxy/init_test.py

